name: Build iOS

on:
  push:
    branches:
      - main  # Se ejecutar치 cuando hagas push a main
  pull_request:
    branches:
      - main  # Se ejecutar치 en PRs dirigidos a main

jobs:
  build_ios:
    runs-on: macos-latest  # Usa un runner de macOS con Xcode instalado

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clona el c칩digo en el runner

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"  # Puedes especificar otra versi칩n

      - name: Install dependencies
        run: flutter pub get  # Descarga paquetes de Flutter

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update  # Instala dependencias de iOS

      - name: Build iOS (no codesign)
        run: flutter build ios --no-codesign  # Compila sin firma
